git:
  submodules: false
language: cpp
compiler:
- clang
before_install:
- sudo add-apt-repository -y ppa:mapnik/boost-backports-1-54
- sudo add-apt-repository -y ppa:kalakris/eigen
- sudo add-apt-repository -y ppa:feelpp/ppa
- sudo apt-get -qq update
- sudo apt-get install -qq libboost1.54-all-dev mpi-default-dev mpi-default-bin libeigen3-dev
  libcln-dev petsc-dev libxml2-dev gmsh bison flex doxygen doxygen-latex transfig
  imagemagick libtbb-dev libann-dev libglpk-dev
- sudo apt-get install libfeel++-dev
install:
- if [ "$CXX" = "clang++" ]; then export CXX="/usr/bin/clang++" CC="/usr/bin/clang";
  fi
- mkdir opt && cd opt && ../configure -f
script:
- make
branches:
  only:
  - master
cache:
- apt
notifications:
  email:
    recipients:
    - po@cemosis.fr
    on_success: change
