steps:
 - name: ':ubuntu: 16.04,clang++-4.0'
   command: .buildkite/steps/build.sh
   agents:
     docker: true
     ubuntu: "16.04"
   env:
     PROJECT: po
     CXX: clang++-4.0
     BUILD_JOBS: 10
     FROM: feelpp/feelpp-toolboxes
     TARGET: ubuntu:16.04
     FEELPP_BRANCH: develop
 - wait
 - name: ':rocket: :whale: deploy :ubuntu: 16.04,clang++-4.0'
   command: .buildkite/steps/release.sh
   agents:
     docker: true
     ubuntu: "16.04"
   branches: develop master
   env:
     PROJECT: po
     TARGET: ubuntu:16.04
