steps:
 - name: ':ubuntu: 17.04,clang++-4.0'
   command: .buildkite/steps/build.sh
   agents:
     docker: true
   env:
     PROJECT: po
     CXX: clang++-4.0
     BUILD_JOBS: 10
     FROM: feelpp/feelpp-toolboxes
     TARGET: ubuntu:17.04
     FEELPP_BRANCH: develop
 - name: ':rocket: :whale: deploy :ubuntu: 17.04,clang++-4.0'
   command: .buildkite/steps/release.sh
   agents:
     docker: true
   branches: develop master
   env:
     PROJECT: po
     TARGET: ubuntu:17.04
